export enum Role {
  USER = 'USER',
  ADMIN = 'ADMIN',
  RECEPTION = 'RECEPTION',
  GRAPHIC_DESIGNER = 'GRAPHIC_DESIGNER',
  OPERATOR = 'OPERATOR',
  FINANCE = 'FINANCE',
  STORE_REPRESENTATIVE = 'STORE_REPRESENTATIVE',
  PURCHASER = 'PURCHASER'
} 