import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1754991977951 implements MigrationInterface {
    name = 'InitialSchema1754991977951'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`user_machine\` (\`id\` varchar(36) NOT NULL, \`userId\` varchar(255) NOT NULL, \`machineId\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_af72a60760d2af7032bae47e7b\` (\`userId\`, \`machineId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`machine\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`status\` tinyint NOT NULL DEFAULT 1, \`description\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_c60541d21fe9d462cb49752d7d\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`unit_category\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`description\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`constant\` tinyint NOT NULL, \`constantValue\` float NOT NULL, UNIQUE INDEX \`IDX_0f1d312e5d4ae66ad45b76e0a1\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`operator_stock\` (\`id\` varchar(36) NOT NULL, \`itemId\` varchar(255) NOT NULL, \`quantity\` int NOT NULL, \`description\` varchar(255) NULL, \`status\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`uomId\` varchar(255) NOT NULL, \`baseUomId\` varchar(255) NOT NULL, \`unit\` float NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`services\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`status\` tinyint NOT NULL DEFAULT 1, \`description\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_019d74f7abcdcb5a0113010cb0\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`non_stock_services\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`status\` tinyint NOT NULL DEFAULT 1, \`description\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_3b75de8d0754fcdb8fe52271b3\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`pricing\` (\`id\` varchar(36) NOT NULL, \`itemId\` varchar(255) NOT NULL, \`serviceId\` varchar(255) NULL, \`nonStockServiceId\` varchar(255) NULL, \`isNonStockService\` tinyint NOT NULL DEFAULT 0, \`sellingPrice\` float NOT NULL, \`costPrice\` float NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`constant\` tinyint NOT NULL DEFAULT 0, \`height\` float NULL, \`width\` float NULL, \`baseUomId\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`vendors\` (\`id\` varchar(36) NOT NULL, \`fullName\` varchar(255) NOT NULL, \`email\` varchar(255) NULL, \`phone\` varchar(255) NOT NULL, \`company\` varchar(255) NULL, \`address\` varchar(255) NULL, \`reference\` varchar(255) NULL, \`description\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_e1f64c741c359e588122ec92a6\` (\`fullName\`), UNIQUE INDEX \`IDX_67ab49bf11bb8ca309d54e5449\` (\`phone\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`purchases\` (\`id\` varchar(36) NOT NULL, \`series\` varchar(255) NOT NULL, \`vendorId\` varchar(255) NOT NULL, \`status\` varchar(255) NOT NULL, \`orderDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`paymentMethod\` varchar(255) NOT NULL, \`amount\` float NOT NULL, \`reference\` varchar(255) NOT NULL, \`totalAmount\` float NOT NULL, \`totalQuantity\` int NOT NULL, \`note\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`purchaserId\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`purchase_item_note\` (\`id\` varchar(36) NOT NULL, \`text\` varchar(255) NOT NULL, \`userId\` varchar(255) NOT NULL, \`date\` datetime NOT NULL, \`hour\` datetime NOT NULL, \`purchaseItemId\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_71f033720e65d50b1fc466b5f4\` (\`userId\`), INDEX \`IDX_c8130ad301f2928a23ff2ca369\` (\`purchaseItemId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`purchase_items\` (\`id\` varchar(36) NOT NULL, \`purchaseId\` varchar(255) NOT NULL, \`itemId\` varchar(255) NOT NULL, \`quantity\` int NOT NULL, \`unitPrice\` float NOT NULL, \`amount\` float NOT NULL, \`description\` varchar(255) NULL, \`status\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`uomId\` varchar(255) NOT NULL, \`baseUomId\` varchar(255) NOT NULL, \`unit\` float NOT NULL, UNIQUE INDEX \`IDX_b51a9c31b0f4f07ed2ac39ef27\` (\`purchaseId\`, \`itemId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`sales\` (\`id\` varchar(36) NOT NULL, \`series\` varchar(255) NOT NULL, \`operatorId\` varchar(255) NOT NULL, \`status\` varchar(255) NOT NULL, \`orderDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`note\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`totalQuantity\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`sales_item_note\` (\`id\` varchar(36) NOT NULL, \`text\` varchar(255) NOT NULL, \`userId\` varchar(255) NOT NULL, \`date\` datetime NOT NULL, \`hour\` datetime NOT NULL, \`saleItemId\` varchar(255) NOT NULL, INDEX \`IDX_fdacec9dee011f00cf271c0d98\` (\`userId\`), INDEX \`IDX_3f31014ee602711ef7855df1db\` (\`saleItemId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`sale_items\` (\`id\` varchar(36) NOT NULL, \`saleId\` varchar(255) NOT NULL, \`itemId\` varchar(255) NOT NULL, \`quantity\` int NOT NULL, \`description\` varchar(255) NULL, \`status\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`uomId\` varchar(255) NOT NULL, \`baseUomId\` varchar(255) NOT NULL, \`unit\` float NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`uom\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`abbreviation\` varchar(255) NOT NULL, \`conversionRate\` float NOT NULL, \`baseUnit\` tinyint NOT NULL DEFAULT 0, \`unitCategoryId\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_0246fd4beee9bba40f4018bbcf\` (\`name\`, \`abbreviation\`, \`unitCategoryId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`attribute\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`value\` varchar(255) NOT NULL, \`itemId\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`itemsId\` varchar(36) NULL, UNIQUE INDEX \`IDX_350fb4f7eb87e4c7d35c97a982\` (\`name\`), UNIQUE INDEX \`IDX_34d21f61011653902cfbb8b55b\` (\`name\`, \`itemId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`discounts\` (\`id\` varchar(36) NOT NULL, \`level\` int NOT NULL, \`itemId\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`percentage\` float NOT NULL, \`unit\` float NOT NULL, \`description\` varchar(255) NULL, UNIQUE INDEX \`IDX_e1dd05494f9be96cb12620eeeb\` (\`itemId\`, \`level\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`items\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`description\` varchar(255) NULL, \`reorder_level\` int NOT NULL, \`initial_stock\` int NOT NULL, \`updated_initial_stock\` int NOT NULL, \`machineId\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`can_be_purchased\` tinyint NOT NULL DEFAULT 1, \`can_be_sold\` tinyint NOT NULL DEFAULT 1, \`quantity\` int NOT NULL, \`unitCategoryId\` varchar(255) NULL, \`defaultUomId\` varchar(255) NULL, \`purchaseUomId\` varchar(255) NULL, UNIQUE INDEX \`IDX_213736582899b3599acaade2cd\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`customers\` (\`id\` varchar(36) NOT NULL, \`fullName\` varchar(255) NOT NULL, \`email\` varchar(255) NULL, \`phone\` varchar(255) NOT NULL, \`company\` varchar(255) NULL, \`address\` varchar(255) NULL, \`description\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_88acd889fbe17d0e16cc4bc917\` (\`phone\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`commission_transactions\` (\`id\` varchar(36) NOT NULL, \`date\` datetime NOT NULL, \`amount\` float NOT NULL, \`percentage\` float NOT NULL, \`commissionId\` varchar(255) NOT NULL, \`paymentMethod\` varchar(255) NOT NULL, \`reference\` varchar(255) NOT NULL, \`status\` varchar(255) NOT NULL, \`description\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`commissions\` (\`id\` varchar(36) NOT NULL, \`orderId\` varchar(255) NOT NULL, \`salesPartnerId\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`totalAmount\` float NOT NULL, \`paidAmount\` float NOT NULL, UNIQUE INDEX \`IDX_f5414c93004f4c88046110d9bd\` (\`orderId\`), UNIQUE INDEX \`REL_f5414c93004f4c88046110d9bd\` (\`orderId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`sales_partners\` (\`id\` varchar(36) NOT NULL, \`fullName\` varchar(255) NOT NULL, \`email\` varchar(255) NULL, \`phone\` varchar(255) NOT NULL, \`company\` varchar(255) NULL, \`address\` varchar(255) NOT NULL, \`description\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_792436093d2a7ae35f35ebb3b0\` (\`email\`), UNIQUE INDEX \`IDX_26bdf5756431e7ca538a808d82\` (\`phone\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`payment_transactions\` (\`id\` varchar(36) NOT NULL, \`date\` datetime NOT NULL, \`paymentTermId\` varchar(255) NOT NULL, \`paymentMethod\` varchar(255) NOT NULL, \`reference\` varchar(255) NOT NULL, \`amount\` float NOT NULL, \`status\` varchar(255) NOT NULL, \`description\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`payment_terms\` (\`id\` varchar(36) NOT NULL, \`orderId\` varchar(255) NOT NULL, \`totalAmount\` float NOT NULL, \`remainingAmount\` float NOT NULL, \`status\` varchar(255) NOT NULL, \`forcePayment\` tinyint NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_fc2ea9567ff5ab710909b61ec0\` (\`orderId\`), UNIQUE INDEX \`REL_fc2ea9567ff5ab710909b61ec0\` (\`orderId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`orders\` (\`id\` varchar(36) NOT NULL, \`series\` varchar(255) NOT NULL, \`customerId\` varchar(255) NOT NULL, \`status\` varchar(255) NOT NULL, \`orderDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`deliveryDate\` datetime NOT NULL, \`totalAmount\` float NOT NULL, \`tax\` float NOT NULL, \`grandTotal\` float NOT NULL, \`totalQuantity\` int NOT NULL, \`internalNote\` varchar(255) NULL, \`paymentTermId\` varchar(255) NULL, \`commissionId\` varchar(255) NULL, \`fileNames\` text NOT NULL, \`adminApproval\` tinyint NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`salesPartnersId\` varchar(255) NULL, \`orderSource\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`order_items\` (\`id\` varchar(36) NOT NULL, \`orderId\` varchar(255) NOT NULL, \`itemId\` varchar(255) NOT NULL, \`serviceId\` varchar(255) NULL, \`nonStockServiceId\` varchar(255) NULL, \`isNonStockService\` tinyint NOT NULL DEFAULT 0, \`width\` float NULL, \`height\` float NULL, \`discount\` float NULL, \`level\` int NOT NULL, \`totalAmount\` float NOT NULL, \`adminApproval\` tinyint NOT NULL, \`uomId\` varchar(255) NOT NULL, \`quantity\` int NOT NULL, \`unitPrice\` float NOT NULL, \`description\` varchar(255) NULL, \`status\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`isDiscounted\` tinyint NOT NULL, \`pricingId\` varchar(255) NOT NULL, \`baseUomId\` varchar(255) NOT NULL, \`unit\` float NOT NULL, \`totalCost\` float NOT NULL DEFAULT '0', \`sales\` float NOT NULL DEFAULT '0', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`order_item_notes\` (\`id\` varchar(36) NOT NULL, \`text\` varchar(255) NOT NULL, \`hour\` datetime NOT NULL, \`date\` datetime NOT NULL, \`userId\` varchar(255) NOT NULL, \`orderItemId\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user\` (\`id\` varchar(36) NOT NULL, \`email\` varchar(255) NOT NULL, \`password\` varchar(255) NOT NULL, \`passwordRT\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`address\` varchar(255) NOT NULL, \`first_name\` varchar(255) NULL, \`gender\` varchar(255) NOT NULL DEFAULT 'MALE', \`last_name\` varchar(255) NULL, \`middle_name\` varchar(255) NULL, \`phone\` varchar(255) NOT NULL, \`profile\` varchar(255) NULL, \`roles\` enum ('USER', 'ADMIN', 'RECEPTION', 'GRAPHIC_DESIGNER', 'OPERATOR', 'FINANCE', 'STORE_REPRESENTATIVE', 'PURCHASER') NOT NULL DEFAULT 'ADMIN', \`confirm_password\` varchar(255) NOT NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, UNIQUE INDEX \`IDX_e12875dfb3b1d92d7d7c5377e2\` (\`email\`), UNIQUE INDEX \`IDX_8e1f623798118e629b46a9e629\` (\`phone\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`fixed_cost\` (\`id\` varchar(36) NOT NULL, \`monthlyFixedCost\` float NOT NULL, \`dailyFixedCost\` float NOT NULL, \`description\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_3824e1902668c6a065fe63be83\` (\`description\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`file_path\` (\`id\` varchar(36) NOT NULL, \`filePath\` varchar(255) NOT NULL, \`fileType\` varchar(255) NOT NULL, \`description\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_c71ccdf7f5b3ab4d5abd99fc3b\` (\`description\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`services_items_items\` (\`servicesId\` varchar(36) NOT NULL, \`itemsId\` varchar(36) NOT NULL, INDEX \`IDX_11e5c165b1866e0fe5dc2f5b17\` (\`servicesId\`), INDEX \`IDX_8d2d12b6b68b9da0d23b9aa72e\` (\`itemsId\`), PRIMARY KEY (\`servicesId\`, \`itemsId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`items_services_services\` (\`itemsId\` varchar(36) NOT NULL, \`servicesId\` varchar(36) NOT NULL, INDEX \`IDX_0af7ef64c6038062e767574dc8\` (\`itemsId\`), INDEX \`IDX_d7864f4f5e2917fc23a6178ba7\` (\`servicesId\`), PRIMARY KEY (\`itemsId\`, \`servicesId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`user_machine\` ADD CONSTRAINT \`FK_7f74ce92adc1bdbd3e525fbe8b7\` FOREIGN KEY (\`machineId\`) REFERENCES \`machine\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_machine\` ADD CONSTRAINT \`FK_531514348ce1804ff125735acbc\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`operator_stock\` ADD CONSTRAINT \`FK_9f880821e14bcfc38e4fa152921\` FOREIGN KEY (\`itemId\`) REFERENCES \`items\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`operator_stock\` ADD CONSTRAINT \`FK_f57c351323d17198f98203f7644\` FOREIGN KEY (\`uomId\`) REFERENCES \`uom\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pricing\` ADD CONSTRAINT \`FK_bd8c383aa0df97a834c3fc77e83\` FOREIGN KEY (\`baseUomId\`) REFERENCES \`uom\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pricing\` ADD CONSTRAINT \`FK_22aa7ee9e019f4f8bf61920da8c\` FOREIGN KEY (\`itemId\`) REFERENCES \`items\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pricing\` ADD CONSTRAINT \`FK_420e1792e18656a1d66a20bab0c\` FOREIGN KEY (\`serviceId\`) REFERENCES \`services\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pricing\` ADD CONSTRAINT \`FK_399b0a2697e25f631095eaadd21\` FOREIGN KEY (\`nonStockServiceId\`) REFERENCES \`non_stock_services\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`purchases\` ADD CONSTRAINT \`FK_780f48bc261cf77f68e27fbc38a\` FOREIGN KEY (\`purchaserId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`purchases\` ADD CONSTRAINT \`FK_ad30f79875fb64a6de23763bf42\` FOREIGN KEY (\`vendorId\`) REFERENCES \`vendors\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`purchase_item_note\` ADD CONSTRAINT \`FK_c8130ad301f2928a23ff2ca3697\` FOREIGN KEY (\`purchaseItemId\`) REFERENCES \`purchase_items\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`purchase_item_note\` ADD CONSTRAINT \`FK_71f033720e65d50b1fc466b5f4a\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`purchase_items\` ADD CONSTRAINT \`FK_684a9853855f5edcd905dc2a9a8\` FOREIGN KEY (\`itemId\`) REFERENCES \`items\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`purchase_items\` ADD CONSTRAINT \`FK_8bafbb5d45827a5d25f5cd3c6f3\` FOREIGN KEY (\`purchaseId\`) REFERENCES \`purchases\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`purchase_items\` ADD CONSTRAINT \`FK_b7b4a9fd8cc9efa37d2488084bc\` FOREIGN KEY (\`uomId\`) REFERENCES \`uom\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sales\` ADD CONSTRAINT \`FK_bcfd467aaf89ac96018400368b7\` FOREIGN KEY (\`operatorId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sales_item_note\` ADD CONSTRAINT \`FK_3f31014ee602711ef7855df1dbc\` FOREIGN KEY (\`saleItemId\`) REFERENCES \`sale_items\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sales_item_note\` ADD CONSTRAINT \`FK_fdacec9dee011f00cf271c0d98d\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sale_items\` ADD CONSTRAINT \`FK_a22cb8ff5a4d3709da216b11610\` FOREIGN KEY (\`itemId\`) REFERENCES \`items\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sale_items\` ADD CONSTRAINT \`FK_c642be08de5235317d4cf3deb40\` FOREIGN KEY (\`saleId\`) REFERENCES \`sales\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sale_items\` ADD CONSTRAINT \`FK_e6f608e57a5ea871bbec9aa3521\` FOREIGN KEY (\`uomId\`) REFERENCES \`uom\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`uom\` ADD CONSTRAINT \`FK_999937e80f724f5a108f45af7bf\` FOREIGN KEY (\`unitCategoryId\`) REFERENCES \`unit_category\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`attribute\` ADD CONSTRAINT \`FK_3f57f0a2bd5fad53d34f1df877f\` FOREIGN KEY (\`itemsId\`) REFERENCES \`items\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`discounts\` ADD CONSTRAINT \`FK_bd1d07c0a61acb7b03cc195509a\` FOREIGN KEY (\`itemId\`) REFERENCES \`items\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD CONSTRAINT \`FK_595a0c1018faf8f48c1ce36a280\` FOREIGN KEY (\`defaultUomId\`) REFERENCES \`uom\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD CONSTRAINT \`FK_9a4ea23f9a8c1e130d7d4c1ddad\` FOREIGN KEY (\`machineId\`) REFERENCES \`machine\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD CONSTRAINT \`FK_c59291c396d452f0c8e419d3e38\` FOREIGN KEY (\`purchaseUomId\`) REFERENCES \`uom\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD CONSTRAINT \`FK_629d91468f5a76f4472c4909261\` FOREIGN KEY (\`unitCategoryId\`) REFERENCES \`unit_category\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`commission_transactions\` ADD CONSTRAINT \`FK_f6fba111295cff46b676a143c0a\` FOREIGN KEY (\`commissionId\`) REFERENCES \`commissions\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`commissions\` ADD CONSTRAINT \`FK_f5414c93004f4c88046110d9bd8\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`commissions\` ADD CONSTRAINT \`FK_6af6faa4f594d828c7e9b784595\` FOREIGN KEY (\`salesPartnerId\`) REFERENCES \`sales_partners\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payment_transactions\` ADD CONSTRAINT \`FK_318578310d536d61d1d94f87fe7\` FOREIGN KEY (\`paymentTermId\`) REFERENCES \`payment_terms\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payment_terms\` ADD CONSTRAINT \`FK_fc2ea9567ff5ab710909b61ec04\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_e5de51ca888d8b1f5ac25799dd1\` FOREIGN KEY (\`customerId\`) REFERENCES \`customers\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_510af4fb2333c7184d568099aa3\` FOREIGN KEY (\`salesPartnersId\`) REFERENCES \`sales_partners\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_e253fbd572683bcc785a70cbca7\` FOREIGN KEY (\`itemId\`) REFERENCES \`items\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_f1d359a55923bb45b057fbdab0d\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_8c20bd83ab9df432718c8fe959d\` FOREIGN KEY (\`pricingId\`) REFERENCES \`pricing\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_9de9472d1a87fd106634222c1b8\` FOREIGN KEY (\`uomId\`) REFERENCES \`uom\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_11690dede7681c3c9ec1fd62d08\` FOREIGN KEY (\`baseUomId\`) REFERENCES \`uom\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_2a8ce0dd0205df008b9e2f09206\` FOREIGN KEY (\`serviceId\`) REFERENCES \`services\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_8f35adad8609a101b60013e008b\` FOREIGN KEY (\`nonStockServiceId\`) REFERENCES \`non_stock_services\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_item_notes\` ADD CONSTRAINT \`FK_ffbf174e0f2412a8352f4d7311b\` FOREIGN KEY (\`orderItemId\`) REFERENCES \`order_items\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_item_notes\` ADD CONSTRAINT \`FK_bfa73e618c9695604eb53c24821\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`services_items_items\` ADD CONSTRAINT \`FK_11e5c165b1866e0fe5dc2f5b178\` FOREIGN KEY (\`servicesId\`) REFERENCES \`services\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`services_items_items\` ADD CONSTRAINT \`FK_8d2d12b6b68b9da0d23b9aa72e3\` FOREIGN KEY (\`itemsId\`) REFERENCES \`items\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`items_services_services\` ADD CONSTRAINT \`FK_0af7ef64c6038062e767574dc88\` FOREIGN KEY (\`itemsId\`) REFERENCES \`items\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`items_services_services\` ADD CONSTRAINT \`FK_d7864f4f5e2917fc23a6178ba73\` FOREIGN KEY (\`servicesId\`) REFERENCES \`services\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`items_services_services\` DROP FOREIGN KEY \`FK_d7864f4f5e2917fc23a6178ba73\``);
        await queryRunner.query(`ALTER TABLE \`items_services_services\` DROP FOREIGN KEY \`FK_0af7ef64c6038062e767574dc88\``);
        await queryRunner.query(`ALTER TABLE \`services_items_items\` DROP FOREIGN KEY \`FK_8d2d12b6b68b9da0d23b9aa72e3\``);
        await queryRunner.query(`ALTER TABLE \`services_items_items\` DROP FOREIGN KEY \`FK_11e5c165b1866e0fe5dc2f5b178\``);
        await queryRunner.query(`ALTER TABLE \`order_item_notes\` DROP FOREIGN KEY \`FK_bfa73e618c9695604eb53c24821\``);
        await queryRunner.query(`ALTER TABLE \`order_item_notes\` DROP FOREIGN KEY \`FK_ffbf174e0f2412a8352f4d7311b\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_8f35adad8609a101b60013e008b\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_2a8ce0dd0205df008b9e2f09206\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_11690dede7681c3c9ec1fd62d08\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_9de9472d1a87fd106634222c1b8\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_8c20bd83ab9df432718c8fe959d\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_f1d359a55923bb45b057fbdab0d\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_e253fbd572683bcc785a70cbca7\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_510af4fb2333c7184d568099aa3\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_e5de51ca888d8b1f5ac25799dd1\``);
        await queryRunner.query(`ALTER TABLE \`payment_terms\` DROP FOREIGN KEY \`FK_fc2ea9567ff5ab710909b61ec04\``);
        await queryRunner.query(`ALTER TABLE \`payment_transactions\` DROP FOREIGN KEY \`FK_318578310d536d61d1d94f87fe7\``);
        await queryRunner.query(`ALTER TABLE \`commissions\` DROP FOREIGN KEY \`FK_6af6faa4f594d828c7e9b784595\``);
        await queryRunner.query(`ALTER TABLE \`commissions\` DROP FOREIGN KEY \`FK_f5414c93004f4c88046110d9bd8\``);
        await queryRunner.query(`ALTER TABLE \`commission_transactions\` DROP FOREIGN KEY \`FK_f6fba111295cff46b676a143c0a\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP FOREIGN KEY \`FK_629d91468f5a76f4472c4909261\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP FOREIGN KEY \`FK_c59291c396d452f0c8e419d3e38\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP FOREIGN KEY \`FK_9a4ea23f9a8c1e130d7d4c1ddad\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP FOREIGN KEY \`FK_595a0c1018faf8f48c1ce36a280\``);
        await queryRunner.query(`ALTER TABLE \`discounts\` DROP FOREIGN KEY \`FK_bd1d07c0a61acb7b03cc195509a\``);
        await queryRunner.query(`ALTER TABLE \`attribute\` DROP FOREIGN KEY \`FK_3f57f0a2bd5fad53d34f1df877f\``);
        await queryRunner.query(`ALTER TABLE \`uom\` DROP FOREIGN KEY \`FK_999937e80f724f5a108f45af7bf\``);
        await queryRunner.query(`ALTER TABLE \`sale_items\` DROP FOREIGN KEY \`FK_e6f608e57a5ea871bbec9aa3521\``);
        await queryRunner.query(`ALTER TABLE \`sale_items\` DROP FOREIGN KEY \`FK_c642be08de5235317d4cf3deb40\``);
        await queryRunner.query(`ALTER TABLE \`sale_items\` DROP FOREIGN KEY \`FK_a22cb8ff5a4d3709da216b11610\``);
        await queryRunner.query(`ALTER TABLE \`sales_item_note\` DROP FOREIGN KEY \`FK_fdacec9dee011f00cf271c0d98d\``);
        await queryRunner.query(`ALTER TABLE \`sales_item_note\` DROP FOREIGN KEY \`FK_3f31014ee602711ef7855df1dbc\``);
        await queryRunner.query(`ALTER TABLE \`sales\` DROP FOREIGN KEY \`FK_bcfd467aaf89ac96018400368b7\``);
        await queryRunner.query(`ALTER TABLE \`purchase_items\` DROP FOREIGN KEY \`FK_b7b4a9fd8cc9efa37d2488084bc\``);
        await queryRunner.query(`ALTER TABLE \`purchase_items\` DROP FOREIGN KEY \`FK_8bafbb5d45827a5d25f5cd3c6f3\``);
        await queryRunner.query(`ALTER TABLE \`purchase_items\` DROP FOREIGN KEY \`FK_684a9853855f5edcd905dc2a9a8\``);
        await queryRunner.query(`ALTER TABLE \`purchase_item_note\` DROP FOREIGN KEY \`FK_71f033720e65d50b1fc466b5f4a\``);
        await queryRunner.query(`ALTER TABLE \`purchase_item_note\` DROP FOREIGN KEY \`FK_c8130ad301f2928a23ff2ca3697\``);
        await queryRunner.query(`ALTER TABLE \`purchases\` DROP FOREIGN KEY \`FK_ad30f79875fb64a6de23763bf42\``);
        await queryRunner.query(`ALTER TABLE \`purchases\` DROP FOREIGN KEY \`FK_780f48bc261cf77f68e27fbc38a\``);
        await queryRunner.query(`ALTER TABLE \`pricing\` DROP FOREIGN KEY \`FK_399b0a2697e25f631095eaadd21\``);
        await queryRunner.query(`ALTER TABLE \`pricing\` DROP FOREIGN KEY \`FK_420e1792e18656a1d66a20bab0c\``);
        await queryRunner.query(`ALTER TABLE \`pricing\` DROP FOREIGN KEY \`FK_22aa7ee9e019f4f8bf61920da8c\``);
        await queryRunner.query(`ALTER TABLE \`pricing\` DROP FOREIGN KEY \`FK_bd8c383aa0df97a834c3fc77e83\``);
        await queryRunner.query(`ALTER TABLE \`operator_stock\` DROP FOREIGN KEY \`FK_f57c351323d17198f98203f7644\``);
        await queryRunner.query(`ALTER TABLE \`operator_stock\` DROP FOREIGN KEY \`FK_9f880821e14bcfc38e4fa152921\``);
        await queryRunner.query(`ALTER TABLE \`user_machine\` DROP FOREIGN KEY \`FK_531514348ce1804ff125735acbc\``);
        await queryRunner.query(`ALTER TABLE \`user_machine\` DROP FOREIGN KEY \`FK_7f74ce92adc1bdbd3e525fbe8b7\``);
        await queryRunner.query(`DROP INDEX \`IDX_d7864f4f5e2917fc23a6178ba7\` ON \`items_services_services\``);
        await queryRunner.query(`DROP INDEX \`IDX_0af7ef64c6038062e767574dc8\` ON \`items_services_services\``);
        await queryRunner.query(`DROP TABLE \`items_services_services\``);
        await queryRunner.query(`DROP INDEX \`IDX_8d2d12b6b68b9da0d23b9aa72e\` ON \`services_items_items\``);
        await queryRunner.query(`DROP INDEX \`IDX_11e5c165b1866e0fe5dc2f5b17\` ON \`services_items_items\``);
        await queryRunner.query(`DROP TABLE \`services_items_items\``);
        await queryRunner.query(`DROP INDEX \`IDX_c71ccdf7f5b3ab4d5abd99fc3b\` ON \`file_path\``);
        await queryRunner.query(`DROP TABLE \`file_path\``);
        await queryRunner.query(`DROP INDEX \`IDX_3824e1902668c6a065fe63be83\` ON \`fixed_cost\``);
        await queryRunner.query(`DROP TABLE \`fixed_cost\``);
        await queryRunner.query(`DROP INDEX \`IDX_8e1f623798118e629b46a9e629\` ON \`user\``);
        await queryRunner.query(`DROP INDEX \`IDX_e12875dfb3b1d92d7d7c5377e2\` ON \`user\``);
        await queryRunner.query(`DROP TABLE \`user\``);
        await queryRunner.query(`DROP TABLE \`order_item_notes\``);
        await queryRunner.query(`DROP TABLE \`order_items\``);
        await queryRunner.query(`DROP TABLE \`orders\``);
        await queryRunner.query(`DROP INDEX \`REL_fc2ea9567ff5ab710909b61ec0\` ON \`payment_terms\``);
        await queryRunner.query(`DROP INDEX \`IDX_fc2ea9567ff5ab710909b61ec0\` ON \`payment_terms\``);
        await queryRunner.query(`DROP TABLE \`payment_terms\``);
        await queryRunner.query(`DROP TABLE \`payment_transactions\``);
        await queryRunner.query(`DROP INDEX \`IDX_26bdf5756431e7ca538a808d82\` ON \`sales_partners\``);
        await queryRunner.query(`DROP INDEX \`IDX_792436093d2a7ae35f35ebb3b0\` ON \`sales_partners\``);
        await queryRunner.query(`DROP TABLE \`sales_partners\``);
        await queryRunner.query(`DROP INDEX \`REL_f5414c93004f4c88046110d9bd\` ON \`commissions\``);
        await queryRunner.query(`DROP INDEX \`IDX_f5414c93004f4c88046110d9bd\` ON \`commissions\``);
        await queryRunner.query(`DROP TABLE \`commissions\``);
        await queryRunner.query(`DROP TABLE \`commission_transactions\``);
        await queryRunner.query(`DROP INDEX \`IDX_88acd889fbe17d0e16cc4bc917\` ON \`customers\``);
        await queryRunner.query(`DROP TABLE \`customers\``);
        await queryRunner.query(`DROP INDEX \`IDX_213736582899b3599acaade2cd\` ON \`items\``);
        await queryRunner.query(`DROP TABLE \`items\``);
        await queryRunner.query(`DROP INDEX \`IDX_e1dd05494f9be96cb12620eeeb\` ON \`discounts\``);
        await queryRunner.query(`DROP TABLE \`discounts\``);
        await queryRunner.query(`DROP INDEX \`IDX_34d21f61011653902cfbb8b55b\` ON \`attribute\``);
        await queryRunner.query(`DROP INDEX \`IDX_350fb4f7eb87e4c7d35c97a982\` ON \`attribute\``);
        await queryRunner.query(`DROP TABLE \`attribute\``);
        await queryRunner.query(`DROP INDEX \`IDX_0246fd4beee9bba40f4018bbcf\` ON \`uom\``);
        await queryRunner.query(`DROP TABLE \`uom\``);
        await queryRunner.query(`DROP TABLE \`sale_items\``);
        await queryRunner.query(`DROP INDEX \`IDX_3f31014ee602711ef7855df1db\` ON \`sales_item_note\``);
        await queryRunner.query(`DROP INDEX \`IDX_fdacec9dee011f00cf271c0d98\` ON \`sales_item_note\``);
        await queryRunner.query(`DROP TABLE \`sales_item_note\``);
        await queryRunner.query(`DROP TABLE \`sales\``);
        await queryRunner.query(`DROP INDEX \`IDX_b51a9c31b0f4f07ed2ac39ef27\` ON \`purchase_items\``);
        await queryRunner.query(`DROP TABLE \`purchase_items\``);
        await queryRunner.query(`DROP INDEX \`IDX_c8130ad301f2928a23ff2ca369\` ON \`purchase_item_note\``);
        await queryRunner.query(`DROP INDEX \`IDX_71f033720e65d50b1fc466b5f4\` ON \`purchase_item_note\``);
        await queryRunner.query(`DROP TABLE \`purchase_item_note\``);
        await queryRunner.query(`DROP TABLE \`purchases\``);
        await queryRunner.query(`DROP INDEX \`IDX_67ab49bf11bb8ca309d54e5449\` ON \`vendors\``);
        await queryRunner.query(`DROP INDEX \`IDX_e1f64c741c359e588122ec92a6\` ON \`vendors\``);
        await queryRunner.query(`DROP TABLE \`vendors\``);
        await queryRunner.query(`DROP TABLE \`pricing\``);
        await queryRunner.query(`DROP INDEX \`IDX_3b75de8d0754fcdb8fe52271b3\` ON \`non_stock_services\``);
        await queryRunner.query(`DROP TABLE \`non_stock_services\``);
        await queryRunner.query(`DROP INDEX \`IDX_019d74f7abcdcb5a0113010cb0\` ON \`services\``);
        await queryRunner.query(`DROP TABLE \`services\``);
        await queryRunner.query(`DROP TABLE \`operator_stock\``);
        await queryRunner.query(`DROP INDEX \`IDX_0f1d312e5d4ae66ad45b76e0a1\` ON \`unit_category\``);
        await queryRunner.query(`DROP TABLE \`unit_category\``);
        await queryRunner.query(`DROP INDEX \`IDX_c60541d21fe9d462cb49752d7d\` ON \`machine\``);
        await queryRunner.query(`DROP TABLE \`machine\``);
        await queryRunner.query(`DROP INDEX \`IDX_af72a60760d2af7032bae47e7b\` ON \`user_machine\``);
        await queryRunner.query(`DROP TABLE \`user_machine\``);
    }

}
